/*
 * Copyright 2026 NXP
 * All rights reserved.
 * MU LLC 2026
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_SD_B1_03 (coord M4), UserLed1 */
/* Routed pin properties */
#define BOARD_INITPINS_UserLed1_PERIPHERAL                                 GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_UserLed1_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_UserLed1_CHANNEL                                       3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_UserLed1_GPIO                                       GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_UserLed1_INIT_GPIO_VALUE                               1U   /*!< GPIO output initial state */
#define BOARD_INITPINS_UserLed1_GPIO_PIN                                      3U   /*!< GPIO pin number */
#define BOARD_INITPINS_UserLed1_GPIO_PIN_MASK                         (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_UserLed1_PORT                                       GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_UserLed1_PIN                                           3U   /*!< PORT pin number */
#define BOARD_INITPINS_UserLed1_PIN_MASK                              (1U << 3U)   /*!< PORT pin mask */

/* GPIO_SD_B1_04 (coord P2), UserLed2 */
/* Routed pin properties */
#define BOARD_INITPINS_UserLed2_PERIPHERAL                                 GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_UserLed2_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_UserLed2_CHANNEL                                       4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_UserLed2_GPIO                                       GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_UserLed2_INIT_GPIO_VALUE                               1U   /*!< GPIO output initial state */
#define BOARD_INITPINS_UserLed2_GPIO_PIN                                      4U   /*!< GPIO pin number */
#define BOARD_INITPINS_UserLed2_GPIO_PIN_MASK                         (1U << 4U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_UserLed2_PORT                                       GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_UserLed2_PIN                                           4U   /*!< PORT pin number */
#define BOARD_INITPINS_UserLed2_PIN_MASK                              (1U << 4U)   /*!< PORT pin mask */

/* GPIO_AD_B1_03 (coord M12), SdPwr */
/* Routed pin properties */
#define BOARD_INITPINS_SdPwr_PERIPHERAL                                    GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_SdPwr_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SdPwr_CHANNEL                                         19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SdPwr_GPIO                                          GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SdPwr_INIT_GPIO_VALUE                                  0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_SdPwr_GPIO_PIN                                        19U   /*!< GPIO pin number */
#define BOARD_INITPINS_SdPwr_GPIO_PIN_MASK                           (1U << 19U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SdPwr_PORT                                          GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SdPwr_PIN                                             19U   /*!< PORT pin number */
#define BOARD_INITPINS_SdPwr_PIN_MASK                                (1U << 19U)   /*!< PORT pin mask */

/* GPIO_AD_B1_04 (coord L12), LcdLed */
/* Routed pin properties */
#define BOARD_INITPINS_LcdLed_PERIPHERAL                                   GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_LcdLed_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LcdLed_CHANNEL                                        20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LcdLed_GPIO                                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LcdLed_INIT_GPIO_VALUE                                 0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_LcdLed_GPIO_PIN                                       20U   /*!< GPIO pin number */
#define BOARD_INITPINS_LcdLed_GPIO_PIN_MASK                          (1U << 20U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LcdLed_PORT                                         GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LcdLed_PIN                                            20U   /*!< PORT pin number */
#define BOARD_INITPINS_LcdLed_PIN_MASK                               (1U << 20U)   /*!< PORT pin mask */

/* GPIO_B1_14 (coord C14), TactBut1 */
/* Routed pin properties */
#define BOARD_INITPINS_TactBut1_PERIPHERAL                                 GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_TactBut1_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_TactBut1_CHANNEL                                      30U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_TactBut1_GPIO                                       GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_TactBut1_GPIO_PIN                                     30U   /*!< GPIO pin number */
#define BOARD_INITPINS_TactBut1_GPIO_PIN_MASK                        (1U << 30U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_TactBut1_PORT                                       GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_TactBut1_PIN                                          30U   /*!< PORT pin number */
#define BOARD_INITPINS_TactBut1_PIN_MASK                             (1U << 30U)   /*!< PORT pin mask */

/* GPIO_AD_B1_06 (coord J12), ExtIn1 */
/* Routed pin properties */
#define BOARD_INITPINS_ExtIn1_PERIPHERAL                                   GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ExtIn1_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ExtIn1_CHANNEL                                        22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ExtIn1_GPIO                                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ExtIn1_GPIO_PIN                                       22U   /*!< GPIO pin number */
#define BOARD_INITPINS_ExtIn1_GPIO_PIN_MASK                          (1U << 22U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ExtIn1_PORT                                         GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ExtIn1_PIN                                            22U   /*!< PORT pin number */
#define BOARD_INITPINS_ExtIn1_PIN_MASK                               (1U << 22U)   /*!< PORT pin mask */

/* GPIO_AD_B1_05 (coord K12), ExtIn2 */
/* Routed pin properties */
#define BOARD_INITPINS_ExtIn2_PERIPHERAL                                   GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ExtIn2_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ExtIn2_CHANNEL                                        21U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ExtIn2_GPIO                                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ExtIn2_GPIO_PIN                                       21U   /*!< GPIO pin number */
#define BOARD_INITPINS_ExtIn2_GPIO_PIN_MASK                          (1U << 21U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ExtIn2_PORT                                         GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ExtIn2_PIN                                            21U   /*!< PORT pin number */
#define BOARD_INITPINS_ExtIn2_PIN_MASK                               (1U << 21U)   /*!< PORT pin mask */

/* GPIO_AD_B1_08 (coord H13), VolumeControl */
/* Routed pin properties */
#define BOARD_INITPINS_VolumeControl_PERIPHERAL                             PWM4   /*!< Peripheral name */
#define BOARD_INITPINS_VolumeControl_SIGNAL                                    A   /*!< Signal name */
#define BOARD_INITPINS_VolumeControl_CHANNEL                                  0U   /*!< Signal channel */

/* GPIO_AD_B1_12 (coord H12), LcdLR */
/* Routed pin properties */
#define BOARD_INITPINS_LcdLr_PERIPHERAL                                    GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_LcdLr_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LcdLr_CHANNEL                                         28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LcdLr_GPIO                                          GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LcdLr_INIT_GPIO_VALUE                                  0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_LcdLr_GPIO_PIN                                        28U   /*!< GPIO pin number */
#define BOARD_INITPINS_LcdLr_GPIO_PIN_MASK                           (1U << 28U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LcdLr_PORT                                          GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LcdLr_PIN                                             28U   /*!< PORT pin number */
#define BOARD_INITPINS_LcdLr_PIN_MASK                                (1U << 28U)   /*!< PORT pin mask */

/* GPIO_AD_B1_13 (coord H11), LcdMode */
/* Routed pin properties */
#define BOARD_INITPINS_LcdMode_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_LcdMode_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LcdMode_CHANNEL                                       29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LcdMode_GPIO                                        GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LcdMode_INIT_GPIO_VALUE                                0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_LcdMode_GPIO_PIN                                      29U   /*!< GPIO pin number */
#define BOARD_INITPINS_LcdMode_GPIO_PIN_MASK                         (1U << 29U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LcdMode_PORT                                        GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LcdMode_PIN                                           29U   /*!< PORT pin number */
#define BOARD_INITPINS_LcdMode_PIN_MASK                              (1U << 29U)   /*!< PORT pin mask */

/* GPIO_AD_B1_14 (coord G12), Lc */
/* Routed pin properties */
#define BOARD_INITPINS_LcdUd_PERIPHERAL                                    GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_LcdUd_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LcdUd_CHANNEL                                         30U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LcdUd_GPIO                                          GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LcdUd_INIT_GPIO_VALUE                                  0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_LcdUd_GPIO_PIN                                        30U   /*!< GPIO pin number */
#define BOARD_INITPINS_LcdUd_GPIO_PIN_MASK                           (1U << 30U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LcdUd_PORT                                          GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LcdUd_PIN                                             30U   /*!< PORT pin number */
#define BOARD_INITPINS_LcdUd_PIN_MASK                                (1U << 30U)   /*!< PORT pin mask */

/* GPIO_AD_B1_15 (coord J14), LcdDithb */
/* Routed pin properties */
#define BOARD_INITPINS_LcdDithb_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_LcdDithb_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LcdDithb_CHANNEL                                      31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LcdDithb_GPIO                                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LcdDithb_INIT_GPIO_VALUE                               0U   /*!< GPIO output initial state */
#define BOARD_INITPINS_LcdDithb_GPIO_PIN                                     31U   /*!< GPIO pin number */
#define BOARD_INITPINS_LcdDithb_GPIO_PIN_MASK                        (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LcdDithb_PORT                                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LcdDithb_PIN                                          31U   /*!< PORT pin number */
#define BOARD_INITPINS_LcdDithb_PIN_MASK                             (1U << 31U)   /*!< PORT pin mask */

/* GPIO_B1_15 (coord B14), TactBut2 */
/* Routed pin properties */
#define BOARD_INITPINS_TactBut2_PERIPHERAL                                 GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_TactBut2_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_TactBut2_CHANNEL                                      31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_TactBut2_GPIO                                       GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_TactBut2_GPIO_PIN                                     31U   /*!< GPIO pin number */
#define BOARD_INITPINS_TactBut2_GPIO_PIN_MASK                        (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_TactBut2_PORT                                       GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_TactBut2_PIN                                          31U   /*!< PORT pin number */
#define BOARD_INITPINS_TactBut2_PIN_MASK                             (1U << 31U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/* GPIO_AD_B1_07 (coord K10), RsRx */
/* Routed pin properties */
#define BOARD_INITRS_UART_RsRx_PERIPHERAL                                LPUART3   /*!< Peripheral name */
#define BOARD_INITRS_UART_RsRx_SIGNAL                                         RX   /*!< Signal name */


/*!
 * @brief RS_RX pin is used as LPUART3_RX
 *
 */
void BOARD_InitRS_UART(void);

/* GPIO_AD_B1_07 (coord K10), RsRx */
/* Routed pin properties */
#define BOARD_INITRS_UART_DEINIT_RsRx_PERIPHERAL                           GPIO1   /*!< Peripheral name */
#define BOARD_INITRS_UART_DEINIT_RsRx_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITRS_UART_DEINIT_RsRx_CHANNEL                                23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITRS_UART_DEINIT_RsRx_GPIO                                 GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITRS_UART_DEINIT_RsRx_GPIO_PIN                               23U   /*!< GPIO pin number */
#define BOARD_INITRS_UART_DEINIT_RsRx_GPIO_PIN_MASK                  (1U << 23U)   /*!< GPIO pin mask */
#define BOARD_INITRS_UART_DEINIT_RsRx_PORT                                 GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITRS_UART_DEINIT_RsRx_PIN                                    23U   /*!< PORT pin number */
#define BOARD_INITRS_UART_DEINIT_RsRx_PIN_MASK                       (1U << 23U)   /*!< PORT pin mask */

/* GPIO_AD_B1_07 (coord K10), RsRx */
/* Routed pin properties */
#define BOARD_INITRS_UART_DEINIT_RsRx_PERIPHERAL                            ADC2   /*!< Peripheral name */
#define BOARD_INITRS_UART_DEINIT_RsRx_SIGNAL                                  IN   /*!< Signal name */
#define BOARD_INITRS_UART_DEINIT_RsRx_CHANNEL                                12U   /*!< Signal channel */

/* GPIO_AD_B1_07 (coord K10), RsRx */
/* Routed pin properties */
#define BOARD_INITRS_UART_DEINIT_RsRx_PERIPHERAL                            CMP1   /*!< Peripheral name */
#define BOARD_INITRS_UART_DEINIT_RsRx_SIGNAL                                  IN   /*!< Signal name */
#define BOARD_INITRS_UART_DEINIT_RsRx_CHANNEL                                 5U   /*!< Signal channel */

/* GPIO_AD_B1_07 (coord K10) */
/* Routed pin properties */
#define BOARD_INITRS_UART_DEINIT_RsRx_PERIPHERAL                            ADC1   /*!< Peripheral name */
#define BOARD_INITRS_UART_DEINIT_RsRx_SIGNAL                                  IN   /*!< Signal name */
#define BOARD_INITRS_UART_DEINIT_RsRx_CHANNEL                                12U   /*!< Signal channel */


/*!
 * @brief This is a de-initialization function for 'BOARD_InitRS_UART' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 */
void BOARD_InitRS_UART_deinit(void);

/* GPIO_AD_B1_07 (coord K10), RsRx */
/* Routed pin properties */
#define BOARD_INITRS_GPIO_RsRx_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITRS_GPIO_RsRx_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITRS_GPIO_RsRx_CHANNEL                                       23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITRS_GPIO_RsRx_GPIO                                        GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITRS_GPIO_RsRx_GPIO_PIN                                      23U   /*!< GPIO pin number */
#define BOARD_INITRS_GPIO_RsRx_GPIO_PIN_MASK                         (1U << 23U)   /*!< GPIO pin mask */
#define BOARD_INITRS_GPIO_RsRx_PORT                                        GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITRS_GPIO_RsRx_PIN                                           23U   /*!< PORT pin number */
#define BOARD_INITRS_GPIO_RsRx_PIN_MASK                              (1U << 23U)   /*!< PORT pin mask */


/*!
 * @brief RS_RX pin is used as GPIO_INPUT
 *
 */
void BOARD_InitRS_GPIO(void);

/* GPIO_AD_B1_07 (coord K10), RsRx */
/* Routed pin properties */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_PERIPHERAL                           GPIO1   /*!< Peripheral name */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_CHANNEL                                23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_GPIO                                 GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_GPIO_PIN                               23U   /*!< GPIO pin number */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_GPIO_PIN_MASK                  (1U << 23U)   /*!< GPIO pin mask */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_PORT                                 GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_PIN                                    23U   /*!< PORT pin number */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_PIN_MASK                       (1U << 23U)   /*!< PORT pin mask */

/* GPIO_AD_B1_07 (coord K10), RsRx */
/* Routed pin properties */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_PERIPHERAL                            ADC2   /*!< Peripheral name */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_SIGNAL                                  IN   /*!< Signal name */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_CHANNEL                                12U   /*!< Signal channel */

/* GPIO_AD_B1_07 (coord K10), RsRx */
/* Routed pin properties */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_PERIPHERAL                            CMP1   /*!< Peripheral name */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_SIGNAL                                  IN   /*!< Signal name */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_CHANNEL                                 5U   /*!< Signal channel */

/* GPIO_AD_B1_07 (coord K10) */
/* Routed pin properties */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_PERIPHERAL                            ADC1   /*!< Peripheral name */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_SIGNAL                                  IN   /*!< Signal name */
#define BOARD_INITRS_GPIO_DEINIT_RsRx_CHANNEL                                12U   /*!< Signal channel */


/*!
 * @brief This is a de-initialization function for 'BOARD_InitRS_GPIO' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 */
void BOARD_InitRS_GPIO_deinit(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
